[package]
name = "wasm_codegen"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
db = { workspace = true }
hir = { workspace = true }
wasm-encoder = { workspace = true }
wasmparser = { workspace = true }
rustc-hash = { workspace = true }
mir = { workspace = true }
debug_format = { workspace = true }
phf = { workspace = true }
wasm_builtins_generated = { path = "../wasm_builtins_generated" }

[dev-dependencies]
auto-lsp = { workspace = true, features = ["lsp_server"] }
ast = { workspace = true }
rstest = { workspace = true }
wasmtime = "45.0.1"
rk = { path = "../cli" }
rand = "0.8"
pollster = "0.4"
futures = "0.3"