[package]
name = "wasm_codegen"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
db = { workspace = true }
hir = { workspace = true }
wasm-encoder = { workspace = true }
rustc-hash = { workspace = true }
mir = { workspace = true }

[dev-dependencies]
auto-lsp = { workspace = true, features = ["lsp_server"] }
ast = { workspace = true }
rstest = { workspace = true }
wasmtime = "43.0.0"
rk = { path = "../cli" }
rand = "0.8"