[package]
name = "hir"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
auto-lsp = { workspace = true }
dashmap = { workspace = true }
ast = { workspace = true }
db = { workspace = true }
rustc-hash = { workspace = true }
tree-sitter-rk = { workspace = true }
bon = { workspace = true }
phf = { workspace = true }
bitflags = { workspace = true }
auto_enums = { workspace = true }
camelpaste = { workspace = true }
fst = { workspace = true }
rayon = { workspace = true }
compact_str = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ariadne = { workspace = true }
ide-diagnostic = { workspace = true }
time = { workspace = true, features = ["macros", "parsing"] }
salsa = { workspace = true }
serde_json = { workspace = true }
