[workspace.package]
authors = ["Clauzel Adrien"]
license = "AGPL-3.0-only"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/ast",
    "crates/db",
    "crates/hir",
    "crates/server",
    "crates/tree-sitter",
    "crates/memory_usage",
    "crates/ide-diagnostic",
    "crates/ide_proto",
    "crates/formatter",
    "vscode/server",
]

[workspace.dependencies]
auto-lsp = { git = "https://github.com/adclz/auto-lsp", rev = "be245971c4c335e607bd3aa82925ea1a91e5f248" }
auto-lsp-codegen = { git = "https://github.com/adclz/auto-lsp", rev = "be245971c4c335e607bd3aa82925ea1a91e5f248" }
log = "0.4.27"
dashmap = "6.1.0"
rustc-hash = "2.1.0"
topiary-core = "0.6.1"
ast = { path = "crates/ast" }
tree-sitter-rk = { path = "crates/tree-sitter" }
server = { path = "crates/server" }
db = { path = "crates/db" }
memory_usage = { path = "crates/memory_usage" }
ide-diagnostic = { path = "crates/ide-diagnostic" }
ide_proto = { path = "crates/ide_proto" }
hir = { path = "crates/hir" }
formatter = { path = "crates/formatter" }
bon = "3.6.4"
phf = { version = "0.11.3", features = ["macros"] }
bitflags = "2.9.1"
auto_enums = "0.8.7"
camelpaste = "0.1.0"
fst = "0.4.7"
rayon = "1.10.0"
compact_str = "0.9.0"
tracing = "0.1"
tracing-subscriber = "0.3"
get-size2 = "0.6.2"
ordermap = "0.5.8"
ariadne = "0.5.1"
time = { version = "0.3.41", features = ["macros", "parsing"] }
rstest = "0.26.1"
insta = "1.13.1"
serde_json = "1.0.109"
stderrlog = "0.6.0"
# salsa version must be kept in sync with auto-lsp's one
salsa = "0.22.0"

[package]
name = "rk-tests"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[profile.release]
opt-level = 3

[dependencies]
auto-lsp = { workspace = true }
ast = { workspace = true }
db = { workspace = true }
hir = { workspace = true }
ide_proto = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
insta = { workspace = true }
ariadne = { workspace = true }
tree-sitter-rk = { workspace = true }
formatter = { workspace = true }
topiary-core = { workspace = true }