[package]
name = "rk-tests"
authors = ["Clauzel Adrien"]
license = "AGPL-3.0-only"
description = ""
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = [
    "crates/ast",
    "crates/db",
    "crates/server",
    "crates/tree-sitter",
    "vscode/server"
]

[workspace.dependencies]
auto-lsp = { git = "https://github.com/adclz/auto-lsp", branch = "capabilities" }
auto-lsp-codegen = { git = "https://github.com/adclz/auto-lsp", branch = "capabilities" }
