// SPDX-FileCopyrightText: 2026 Clauzel Adrien
// SPDX-License-Identifier: AGPL-3.0-only

//! What a report says after its code: the diagnostic's title, as
//! `crates/doc/examples/<code>.md` gives it, starting in lower case unless
//! it starts with a keyword. `src/tests/diagnostic_shape.rs` holds the two
//! together.

/// `(code, header)`, sorted by code.
pub const HEADERS: &[(&str, &str)] = &[
    ("E0001", "syntax error"),
    ("E0002", "missing element"),
    ("E0003", "missing variable type"),
    ("E0004", "unexpected variable initialization"),
    ("E0005", "empty right-hand side of assignment"),
    ("E0006", "invalid assignment sign '='"),
    ("E0007", "invalid assignment sign ':'"),
    ("E0008", "invalid assignment sign '=>' in assignment"),
    ("E0009", "invalid assignment sign '=' in FOR list"),
    ("E0010", "invalid assignment sign ':' in FOR list"),
    ("E0011", "invalid assignment sign '=>' in FOR list"),
    ("E0012", "assignment sign ':=' in a condition"),
    ("E0013", "assignment to a function call"),
    ("E0014", "incomplete edge qualifier"),
    ("E0015", "THIS after a dot in a path"),
    ("E0016", "SUPER after a dot in a path"),
    ("E0017", "VAR not allowed in this context"),
    ("E0018", "VAR_IN_OUT not allowed in this context"),
    ("E0019", "VAR_TEMP not allowed in this context"),
    ("E0020", "VAR_EXTERNAL not allowed in this context"),
    ("E0021", "VAR_GLOBAL not allowed in this context"),
    ("E0022", "VAR_ACCESS not allowed in this context"),
    ("E0023", "VAR_CONFIG not allowed in this context"),
    ("E0024", "PROGRAM in a NAMESPACE"),
    ("E0025", "CONFIGURATION in a NAMESPACE"),
    ("E0026", "variables after methods in a FUNCTION_BLOCK"),
    ("E0027", "variables after methods in a CLASS"),
    ("E0028", "METHOD declared in a body"),
    ("E0029", "variadic parameter outside a FUNCTION or METHOD"),
    ("E0101", "duplicate variable"),
    ("E0102", "duplicate POU"),
    ("E0103", "duplicate parameter"),
    ("E0104", "duplicate struct field"),
    ("E0105", "duplicate enum variant"),
    ("E0106", "duplicate field in an initializer"),
    ("E0107", "return value declared again"),
    ("E0108", "duplicate method declaration"),
    ("E0109", "duplicate method prototype"),
    ("E0110", "duplicate inherited method"),
    ("E0111", "duplicate USING"),
    ("E0112", "duplicate PROGRAM"),
    ("E0113", "duplicate PROGRAM instance"),
    ("E0114", "duplicate TASK"),
    ("E0115", "duplicate RESOURCE"),
    ("E0201", "unknown name"),
    ("E0202", "unknown field"),
    ("E0203", "unknown name in a namespace"),
    ("E0204", "unknown namespace in USING"),
    ("E0205", "ambiguous name"),
    ("E0206", "VAR_EXTERNAL without a VAR_GLOBAL"),
    ("E0207", "VAR_EXTERNAL type mismatch"),
    ("E0208", "RETAIN in a stateless POU"),
    ("E0209", "variable out of reach"),
    ("E0301", "type mismatch"),
    ("E0302", "types not comparable"),
    ("E0303", "types not addable"),
    ("E0304", "types not multiplicable"),
    ("E0305", "operator not supported by the type"),
    ("E0306", "literal out of range"),
    ("E0307", "negative literal for an unsigned type"),
    ("E0308", "literal of the wrong kind"),
    ("E0309", "malformed duration"),
    ("E0310", "malformed date"),
    ("E0311", "malformed time of day"),
    ("E0312", "malformed date and time"),
    ("E0313", "CHAR literal of the wrong length"),
    ("E0314", "STRING literal over its capacity"),
    ("E0315", "STRING length not constant"),
    ("E0316", "FUNCTION used as a type"),
    ("E0317", "type name used as a value"),
    ("E0318", "assignment to an instance"),
    ("E0319", "assignment to a missing return value"),
    ("E0320", "negative STRING length"),
    ("E0401", "initial value not constant"),
    ("E0402", "function call in a repeat count"),
    ("E0403", "elementary type initialized with parentheses"),
    ("E0404", "write to a constant"),
    ("E0405", "initializer for a member that takes none"),
    ("E0406", "read before initialization"),
    ("E0407", "aggregate default on a FUNCTION or METHOD input"),
    ("E0501", "invalid array lower bound"),
    ("E0502", "invalid array upper bound"),
    ("E0503", "upper bound below the lower bound"),
    ("E0504", "array index not an integer"),
    ("E0505", "invalid repeat count"),
    ("E0506", "constant index out of bounds"),
    ("E0507", "too many elements in array initializer"),
    ("E0508", "index into a non-array type"),
    ("E0509", "array conformands not supported"),
    ("E0510", "incomplete subscript"),
    ("E0601", "ENUM base type not an integer"),
    ("E0602", "not an ENUM type"),
    ("E0603", "unknown ENUM variant"),
    ("E0604", "ENUM variant value not constant"),
    ("E0605", "ENUM value outside its storage type"),
    ("E0701", "subrange base type not an integer"),
    ("E0702", "value outside the subrange"),
    ("E0703", "subrange bound not constant"),
    ("E0704", "subrange mismatch across a reference"),
    ("E0705", "subrange bounds reversed"),
    ("E0801", "wrong number of arguments"),
    ("E0802", "missing required parameter"),
    ("E0803", "unknown input parameter"),
    ("E0804", "unknown output parameter"),
    ("E0805", "output parameter used as input"),
    ("E0806", "VAR_IN_OUT argument not a variable"),
    ("E0807", "VAR_IN_OUT bound with =>"),
    ("E0808", "call of a non-callable type"),
    ("E0809", "ambiguous overloaded call"),
    ("E0810", "no matching overload"),
    ("E0811", "variadic parameter of a composite type"),
    ("E0812", "more than one variadic parameter"),
    ("E0813", "variadic call without arguments"),
    ("E0814", "not a variadic parameter"),
    ("E0815", "variadic parameter beside other inputs"),
    ("E0816", "variadic parameter used outside a fold"),
    ("E0901", "dereference of a non-reference type"),
    ("E0902", "possibly null dereference"),
    ("E0903", "reference outlives its storage"),
    ("E0904", "reference in RETAIN storage"),
    ("E1001", "access to a PRIVATE item"),
    ("E1002", "access to a PROTECTED item"),
    ("E1003", "access to an INTERNAL item"),
    ("E1004", "access to an INTERNAL namespace"),
    ("E1005", "call of a PRIVATE function"),
    ("E1006", "specifier not applicable to a FUNCTION"),
    ("E1007", "access to a test-only item"),
    ("E1101", "more than one EXTENDS clause"),
    ("E1102", "more than one IMPLEMENTS clause"),
    ("E1103", "IMPLEMENTS before EXTENDS"),
    ("E1104", "FINAL type extended"),
    ("E1105", "THIS in a FUNCTION"),
    ("E1106", "SUPER in a FUNCTION or PROGRAM"),
    ("E1107", "SUPER without an EXTENDS clause"),
    ("E1108", "SUPER() outside a function block body"),
    ("E1109", "SUPER() called in a method"),
    ("E1110", "SUPER() called more than once"),
    ("E1111", "SUPER() called inside a loop"),
    ("E1112", "missing OVERRIDE keyword"),
    ("E1113", "OVERRIDE without a base method"),
    ("E1114", "FINAL method overridden"),
    ("E1115", "inherited variable redeclared"),
    ("E1116", "missing ABSTRACT method implementation"),
    ("E1117", "ABSTRACT method in a concrete POU"),
    ("E1118", "instantiation of an ABSTRACT type"),
    ("E1119", "unimplemented interface method"),
    ("E1120", "access specifier on interface method prototype"),
    ("E1121", "interface type outside a parameter"),
    ("E1122", "interface as a return type"),
    ("E1123", "interface nested in an aggregate"),
    ("E1124", "assignment to an interface parameter"),
    ("E1125", "method parameter count mismatch"),
    ("E1126", "method parameter type mismatch"),
    ("E1127", "method return type mismatch"),
    ("E1128", "method parameter name mismatch"),
    ("E1129", "method parameter section mismatch"),
    ("E1130", "base of the wrong kind"),
    ("E1131", "method parameter default mismatch"),
    ("E1132", "SUPER() with a CLASS base"),
    ("E1133", "SUPER calls a method with no body"),
    ("E1134", "ABSTRACT method with a body"),
    ("E1135", "interface method implemented without PUBLIC"),
    ("E1201", "EXIT outside loop"),
    ("E1202", "CONTINUE outside loop"),
    ("E1203", "FOR control not a variable"),
    ("E1204", "FOR step not a nonzero constant"),
    ("E1205", "CASE label not constant"),
    ("E1206", "FOR counter not an integer"),
    ("E1207", "CASE selector of the wrong type"),
    ("E1208", "empty CASE range"),
    ("E1301", "type contains itself"),
    ("E1302", "types contain each other"),
    ("E1401", "no project configuration"),
    ("E1402", "more than one CONFIGURATION"),
    ("E1403", "more than one RESOURCE"),
    ("E1404", "TASK or PROGRAM outside a RESOURCE"),
    ("E1405", "missing PRIORITY in TASK"),
    ("E1406", "unusable TASK priority"),
    ("E1407", "INTERVAL after PRIORITY in TASK"),
    ("E1408", "SINGLE after INTERVAL in TASK"),
    ("E1409", "SINGLE after PRIORITY in TASK"),
    ("E1410", "unschedulable TASK"),
    ("E1411", "unknown TASK reference"),
    ("E1412", "program instance without a task"),
    ("E1413", "unknown instance in VAR_CONFIG"),
    ("E1414", "unknown field in VAR_CONFIG"),
    ("E1415", "VAR_ACCESS type mismatch"),
    ("E1417", "address not locatable"),
    ("E1418", "unknown multibit access size"),
    ("E1419", "write to an input location"),
    ("E1420", "RETAIN on an I/O location"),
    ("E1421", "duplicate location"),
    ("E1422", "location type mismatch"),
    ("E1423", "part of a wider address"),
    ("E1424", "location refused"),
    ("E1425", "variable not located"),
    ("E1426", "configuration entry refused"),
    ("E1427", "located variable overwritten"),
    ("E1428", "program configuration element refused"),
    ("E1429", "partial access out of range"),
    ("E1501", "extern pragma outside a FUNCTION"),
    ("E1502", "not representable on an extern FUNCTION"),
    ("E1503", "test pragma outside a FUNCTION"),
    ("E1504", "wasm pragma outside a FUNCTION"),
    ("E1505", "unknown wasm instruction"),
    ("E1506", "wasm operand not declared"),
    ("E1507", "wasm operands of the wrong type"),
    ("E1508", "export pragma outside a FUNCTION"),
    ("E1509", "FUNCTION not exportable"),
    ("L0001", "{info} notice"),
    ("L0002", "{warn} notice"),
    ("L0003", "pragma without effect on the POU"),
    ("L0004", "{once} POU called more than once"),
    ("L0005", "unknown rule name in {allow}"),
    ("L0101", "unreachable code"),
    ("L0102", "division by zero"),
    ("L0103", "constant condition"),
    ("L0104", "self-assignment"),
    ("L0105", "self-comparison"),
    ("L0106", "subtraction from self"),
    ("L0107", "identity operation"),
    ("L0108", "identical subexpressions"),
    ("L0109", "duplicate CASE value"),
    ("L0110", "FOR loop step sign mismatch"),
    ("L0111", "constant FOR loop bounds"),
    ("L0112", "FOR control variable written"),
    ("L0113", "assignment to input variable"),
    ("L0114", "missing return assignment"),
    ("L0115", "variable named after its POU"),
    ("L0116", "method variable named after a member"),
    ("L0117", "external instance mutation"),
    ("L0118", "global accessed without VAR_EXTERNAL"),
    ("L0119", "instance in a stateless POU"),
    ("L0120", "variable and method with the same name"),
    ("L0121", "STRING with a Latin-1 escape"),
    ("L0122", "recursive call"),
    ("L0123", "negative radix literal"),
    ("L0201", "unused variable"),
    ("L0202", "variable named after a POU"),
    ("L0203", "duplicate variable section"),
    ("L0204", "duplicate namespace"),
    ("L0205", "duplicate configuration"),
    ("L0206", "uninitialized output"),
    ("L0207", "negated condition"),
    ("L0208", "negated comparison"),
    ("L0209", "boolean comparison"),
    ("L0210", "redundant NOT"),
    ("L0211", "unnecessary ELSE"),
    ("L0212", "single-element array"),
    ("L0213", "explicit default FOR step"),
    ("L0301", "unused import"),
    ("L0302", "unused return value"),
    ("L0303", "missing input parameter"),
    ("L0304", "CASE without ELSE"),
    ("L0305", "empty body"),
    ("L0306", "empty IF branch"),
    ("L0307", "empty CASE branch"),
    ("L0308", "empty loop body"),
    ("L0309", "empty type declaration"),
    ("L0310", "effectless statement"),
    ("L0311", "unnecessary parentheses"),
    ("L0312", "collapsible IF"),
    ("L0313", "literal on the left of a comparison"),
];

/// The header of `code`, or the empty string for a code with no entry.
pub fn header(code: &str) -> &'static str {
    HEADERS
        .binary_search_by(|(c, _)| c.cmp(&code))
        .map_or("", |i| HEADERS[i].1)
}
