[package]
name = "doc"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "generate-docs"
path = "src/main.rs"

[dependencies]
ast = { workspace = true }
db = { workspace = true }
hir = { workspace = true }
linter = { workspace = true }
ide_diagnostic = { workspace = true }
ariadne = { workspace = true }
ansi-to-html = "0.2"
auto-lsp = { workspace = true }
