[package]
name = "doc"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "generate-docs"
path = "src/main.rs"

[dependencies]
ast = { workspace = true }
db = { workspace = true }
hir = { workspace = true }
linter = { workspace = true }
ide_diagnostic = { workspace = true }
ariadne = { workspace = true }
ansi-to-html = "0.2"
auto-lsp = { workspace = true }
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
tree-sitter = { workspace = true }
tree-sitter-highlight = "0.26"
tree-sitter-rk = { version = "0.1.0", path = "../tree-sitter" }
serde_json.workspace = true
flate2 = "1.1.10"
tar = "0.4.46"
sha2 = "0.10"
