//! `rk explain <code>` — the diagnostics reference at the terminal.
//!
//! Reads the same committed artifact the documentation site serves
//! (`docs/static/diagnostics/diagnostics.json`, generated by
//! `generate-docs` from `crates/doc/src/examples.rs`), embedded at build
//! time. Plain text on stdout, so agents and editors can consume it as
//! easily as humans.

use serde::Deserialize;

use crate::error::{CliError, CliResult};

const REFERENCE: &str = include_str!("../../../../docs/static/diagnostics/diagnostics.json");

#[derive(Deserialize)]
struct Entry {
    code: String,
    category: String,
    title: String,
    description: String,
    sources: Vec<String>,
}

pub fn run_explain(code: &str) -> CliResult<()> {
    let entries: Vec<Entry> = serde_json::from_str(REFERENCE)
        .map_err(|e| CliError::Message(format!("malformed diagnostics reference: {e}")))?;

    let needle = code.trim().to_ascii_uppercase();
    let Some(entry) = entries.into_iter().find(|e| e.code == needle) else {
        return Err(CliError::Message(format!(
            "unknown diagnostic code '{}' — codes look like E0301 or L0002",
            code.trim()
        )));
    };

    println!("{}: {} ({})", entry.code, entry.title, entry.category);
    println!();
    println!("{}", entry.description);
    for source in &entry.sources {
        println!();
        println!("example:");
        for line in source.trim_matches('\n').lines() {
            println!("    {line}");
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The embedded artifact must parse and cover the codes explain promises.
    #[test]
    fn reference_parses_and_knows_the_classics() {
        let entries: Vec<Entry> = serde_json::from_str(REFERENCE).expect("valid json");
        assert!(entries.len() > 200, "reference looks truncated");
        for code in ["E0301", "E0101", "E0225"] {
            assert!(entries.iter().any(|e| e.code == code), "{code} missing");
        }
    }
}
