[package]
name = "tree-sitter-rk"
description = "Structured Text grammar for tree-sitter"
version = "0.1.0"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "structured-text"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/adclz/rk"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = { workspace = true }

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = { workspace = true }
