[package]
name = "ide_proto"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
auto-lsp = { workspace = true }
hir = { workspace = true }
ast = { workspace = true }
db = { workspace = true }
linter = { workspace = true }
index = { workspace = true }
serde_json = { workspace = true }
camelpaste = { workspace = true }
rustc-hash = { workspace = true }
tree-sitter-rk = { workspace = true }
tracing = { workspace = true }
salsa = { workspace = true }
bitflags = { workspace = true }