[package]
name = "rk-benchmark"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[lib]
bench = false
doctest = false

[dependencies]
auto-lsp = { workspace = true }
ast = { workspace = true }
db = { workspace = true }
hir = { workspace = true }
linter = { workspace = true }
formatter = { workspace = true }
mir = { workspace = true }
wasm_codegen = { workspace = true }

[[bench]]
name = "parse"
harness = false

[[bench]]
name = "hir"
harness = false

[[bench]]
name = "incremental"
harness = false

[[bench]]
name = "linter"
harness = false

[[bench]]
name = "formatter"
harness = false

[[bench]]
name = "codegen"
harness = false

[dev-dependencies]
divan = { workspace = true }
