[package]
name = "db"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false


[dependencies]
auto-lsp = { workspace = true }
ast = { workspace = true }
ide_diagnostic = { workspace = true }
dashmap = { workspace = true, features = ["rayon"] }
salsa = { workspace = true }
rayon = { workspace = true }
dirs = { workspace = true }
