name: rust
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.js"
      - "**.ts"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.js"
      - "**.ts"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h
      - name: Install wasm32
        run: rustup target add wasm32-unknown-unknown
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Test workspace
        run: cargo-nextest ntr --workspace